### ISSUE TITLE
Failed to call onError method of POJO end point for POJO

### ISSUE THREAD

**Issue by webonix** [lucee/extension-websocket#7]
```
2024-04-23 15:18:53 calling [onMessage] via reflection, Lucee restart needed!
2024-04-23 15:18:53 calling [onError] via reflection, Lucee restart needed!
2024-04-23 15:18:53 23-Apr-2024 07:18:53.209 SEVERE [http-nio-8888-exec-4] org.apache.tomcat.websocket.pojo.PojoEndpointBase.onError Failed to call onError method of POJO end point for POJO of type [org.lucee.extension.websocket.JavaxWebSocketEndpoint]
2024-04-23 15:18:53  java.lang.reflect.InvocationTargetException
2024-04-23 15:18:53     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-04-23 15:18:53     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-04-23 15:18:53     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-04-23 15:18:53     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2024-04-23 15:18:53     at org.apache.tomcat.websocket.pojo.PojoEndpointBase.onError(PojoEndpointBase.java:130)
2024-04-23 15:18:53     at org.apache.tomcat.websocket.WsFrameBase.handleThrowableOnSend(WsFrameBase.java:559)
2024-04-23 15:18:53     at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:398)
2024-04-23 15:18:53     at org.apache.tomcat.websocket.server.WsFrameServer.sendMessageText(WsFrameServer.java:119)
2024-04-23 15:18:53     at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:495)
2024-04-23 15:18:53     at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:294)
2024-04-23 15:18:53     at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:133)
2024-04-23 15:18:53     at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:82)
2024-04-23 15:18:53     at org.apache.tomcat.websocket.server.WsFrameServer.doOnDataAvailable(WsFrameServer.java:171)
2024-04-23 15:18:53     at org.apache.tomcat.websocket.server.WsFrameServer.notifyDataAvailable(WsFrameServer.java:151)
2024-04-23 15:18:53     at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler.upgradeDispatch(WsHttpUpgradeHandler.java:148)
2024-04-23 15:18:53     at org.apache.coyote.http11.upgrade.UpgradeProcessorInternal.dispatch(UpgradeProcessorInternal.java:54)
2024-04-23 15:18:53     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:53)
2024-04-23 15:18:53     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:770)
2024-04-23 15:18:53     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1415)
2024-04-23 15:18:53     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
2024-04-23 15:18:53     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2024-04-23 15:18:53     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2024-04-23 15:18:53     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
2024-04-23 15:18:53     at java.base/java.lang.Thread.run(Thread.java:829)
2024-04-23 15:18:53 Caused by: lucee.runtime.exp.NativeException: java.lang.NullPointerException
2024-04-23 15:18:53     at org.lucee.extension.websocket.util.WSUtil.getLog(WSUtil.java:434)
2024-04-23 15:18:53     at org.lucee.extension.websocket.util.WSUtil.info(WSUtil.java:381)
2024-04-23 15:18:53     at org.lucee.extension.websocket.BaseWebSocketEndpoint.onError(BaseWebSocketEndpoint.java:225)
2024-04-23 15:18:53     at org.lucee.extension.websocket.JavaxWebSocketEndpoint.onError(JavaxWebSocketEndpoint.java:42)
2024-04-23 15:18:53     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2024-04-23 15:18:53     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2024-04-23 15:18:53     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2024-04-23 15:18:53     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2024-04-23 15:18:53     at lucee.runtime.reflection.pairs.MethodInstance.invoke(MethodInstance.java:56)
2024-04-23 15:18:53     at lucee.runtime.reflection.Reflector.callMethod(Reflector.java:1063)
2024-04-23 15:18:53     at lucee.runtime.util.ClassUtilImpl.callMethod(ClassUtilImpl.java:189)
2024-04-23 15:18:53     at org.lucee.extension.websocket.BaseWebSocketEndpoint.on(BaseWebSocketEndpoint.java:81)
2024-04-23 15:18:53     at org.lucee.extension.websocket.BaseWebSocketEndpoint.onError(BaseWebSocketEndpoint.java:221)
2024-04-23 15:18:53     at org.lucee.extension.websocket.JavaxWebSocketEndpoint.onError(JavaxWebSocketEndpoint.java:42)
2024-04-23 15:18:53     ... 24 more
2024-04-23 15:18:53 Caused by: java.lang.NullPointerException
2024-04-23 15:18:53     ... 38 more
2024-04-23 15:18:53 
```

**Comment by webonix** [comment]
after getting this error, the thread stops running

>2024-04-23 15:18:53 calling [onMessage] via reflection, Lucee restart needed!
>2024-04-23 15:18:53 calling [onError] via reflection, Lucee restart needed!

```
public static function onFirstOpen(wsclients) {
		systemOutput("--- events WS onFirstOpen(#arguments.KeyList()#) ---",1,0);

		static.wsclients = arguments.wsclients; // store it so every functions can use it
		variables.connections = {};

		// monitor Redis Queue - wsEvents:messagesOut
		thread  
			timeout=0
			// oClients=static.wsclients  
		{
            while(true) {
                try {
					sleep(1000);
					
					var item = redisCommand(
						arguments = ["rpop", 'wsEvents:messagesOut'],
						cache     =  'wsConnections'
					);
					systemOutput('AJM redisCommand loop [#!isNull(item)#] for oClients.size() clients',1,0);
					if( !isNull(item) ) {
						//oClients.broadcast(item);
					}
					
                }
                catch(e) {
					systemOutput('Error:#e.message# 
                    sleep(10000);
                }
            }
        }
	}
```

**Comment by michaeloffner** [comment]
https://github.com/lucee/extension-websocket/commit/a7629eeec9396a553e63bae284ebf7a2b02ea6f2
